# Mock Hackathon

In [2]:
import pandas as pd
import os

sample submission

In [ ]:
local_path = os.path.join('data','sample_submission.csv')
url = 'https://raw.githubusercontent.com/samsung-ai-course/8th-9th-edition/refs/heads/main/Chapter%205%20-%20Responsible%20AI/data/sample_submission.csv'
df_sample_submission = pd.read_csv(url)
df_sample_submission

         id  proba
0      7991    0.5
1     31470    0.5
2     27345    0.5
3      7509    0.5
4     61999    0.5
...     ...    ...
4495  87722    0.5
4496  16925    0.5
4497  35300    0.5
4498  86129    0.5
4499  72473    0.5

[4500 rows x 2 columns]

test data to create submissions on

In [ ]:
local_path = os.path.join('data','test.csv')
url = 'https://raw.githubusercontent.com/samsung-ai-course/8th-9th-edition/refs/heads/main/Chapter%205%20-%20Responsible%20AI/data/test.csv'
df_test = pd.read_csv(url, low_memory=False)
df_test

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance
0,0x44d1,CUS_0xb1da,August,Paulj,35,671-03-8487,Doctor,110721.66_,9259.805000,3,...,6.0,_,281.42,28.620300,26 Years and 6 Months,No,209.245449,131.5562784570291,High_spent_Medium_value_payments,835.178773
1,0xce64,CUS_0x6f55,July,Leongr,53,923-48-1651,Writer,18579.36,1298.280000,0,...,1.0,Good,1329.98,29.681948,29 Years and 9 Months,No,16.174857,150.7169895127531,!@9#%8,252.936153
2,0xb63b,CUS_0x880b,February,Jones Lisag,21,790-45-5982,Writer,7830.03,775.502500,8,...,8.0,Bad,1255.57,27.130360,5 Years and 5 Months,Yes,31.593600,47.532261487489116,Low_spent_Medium_value_payments,278.424389
3,0x41ff,CUS_0x4a83,June,NaN,19,408-42-1764,Engineer,35322.24_,2805.520000,5,...,2.0,_,907.76,34.294300,30 Years and 6 Months,NM,61.725788,185.52382946164252,!@9#%8,293.302383
4,0x18145,CUS_0x7d6c,August,Eileenc,24,424-12-8828,Scientist,17307708.0,7093.165000,5,...,4.0,Standard,218.44,39.448697,28 Years and 0 Months,No,72.633969,371.05530058370016,High_spent_Small_value_payments,525.627230
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,0x21800,CUS_0x4bef,March,McAllisterb,18,783-63-1238,Journalist,38505.32,2922.147520,7,...,4.0,Standard,2159.19,25.539420,10 Years and 1 Months,Yes,214.658697,24.791647923065504,High_spent_Large_value_payments,450.756468
4496,0x792b,CUS_0xa6f9,June,Kevin Drawbaughf,29,#F%$D@*&8,Scientist,46722.72,3781.560000,9,...,16.0,_,4764.13,28.066109,8 Years and 10 Months,Yes,284.659751,279.81362006108316,Low_spent_Small_value_payments,103.682629
4497,0xe4d6,CUS_0x262e,May,Karina Grazinax,23,216-94-2190,Journalist,8983.565,645.630417,6,...,8.0,Standard,1270.65,28.235121,15 Years and 0 Months,Yes,9.885125,16.832254838086712,Low_spent_Medium_value_payments,317.845662
4498,0x20eab,CUS_0x3ce2,February,Suzannek,29,776-82-8001,Engineer,14095.93,1310.660833,9,...,7.0,Bad,2790.05,27.949570,1 Years and 6 Months,Yes,37.745141,54.5238056664076,High_spent_Small_value_payments,298.797136
4499,0x1bea7,CUS_0x9e80,February,Noelc,39,209-05-4739,Journalist,104455.02,NaN,4,...,9.0,Good,1222.3,40.053292,28 Years and 2 Months,No,215.110323,132.88148129541378,High_spent_Large_value_payments,781.266696

historical data to train models on

In [ ]:
local_path = os.path.join('data','history.csv')
url = 'https://raw.githubusercontent.com/samsung-ai-course/8th-9th-edition/refs/heads/main/Chapter%205%20-%20Responsible%20AI/data/history.csv'
df_train = pd.read_csv(url, low_memory=False)
print(df_train.shape)
df_train.head(3)

(33412, 28)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
2,0x1607,CUS_0xd40,June,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,27.262259,22 Years and 6 Months,No,49.574949,62.430172331195294,!@9#%8,340.4792117872438,Good

# Exercise 1

Train a model on this data and perform threshold analysis. Create a submission that maximizes for f1_score

# Exercise 2

Assume the cost of a False positive is 30€ and the benefit of a True Positive is 70€, create a submission that maximizes for this.

# Exercise 3

Evaluate the fairness of your model using [aequitas](https://github.com/dssg/aequitas)